### ISSUE TITLE
Famo.us University not working..

### ISSUE THREAD

**Issue by Urigo** [Famous/famous#629] opened 2015-02-08 22:50 UTC
When surfing to http://famo.us/university/home/    

Chrome Version 40.0.2214.94 (64-bit)
Mac OS X 10.10.2 (14C109)

![screen shot 2015-02-08 at 2 48 54 pm](https://cloud.githubusercontent.com/assets/1297448/6098930/b721fdce-afa1-11e4-866a-34380342715e.png)

**Comment by michaelobriena** [comment] 2015-02-08 23:25
@TheAlphaNerd @matthewtoast @zackbrown

**Comment by MylesBorins** [comment] 2015-02-08 23:26
I cannot seem to reproduce on my machine... Looks like famo.us angular
needs a bump to me

**Comment by michaelobriena** [comment] 2015-02-08 23:29
It looks fine on my side also.

**Comment by MylesBorins** [comment] 2015-02-08 23:36
This is not the first time I have heard about this bug… and I am still get the null bug.  I believe that the landing page is a different app than university itself.

@Urigo can you try this link (directly to lesson)

--> http://famo.us/university/lessons/#/famous-101/displaying/1

**Comment by Urigo** [comment] 2015-02-08 23:43
Yes, this link works for me (and the first one still doesn't work)

**Comment by MylesBorins** [comment] 2015-02-08 23:47
@jordanpapaleo can you take a look at this asap??? /cc @zackbrown

**Comment by zackbrown** [comment] 2015-02-10 23:45
I'm unable to reproduce this on OSX 10.10.1, Chrome 39, Chrome 40, Safari 8.0, or Firefox 35.  Have you tried disabling extensions?  From your screenshot it looks like you may have an ad blocker installed, which could (?) be interfering with asset downloads.  Are any of the asset downloads failing for you? (via the Chrome dev tools "Network" tab or any sort of console exposed by your ad blocker.)

**Comment by Urigo** [comment] 2015-02-10 23:49
Removed all extensions - still the same (also looked at the network tab and it looks like everything is loading):
![screen shot 2015-02-10 at 3 47 36 pm](https://cloud.githubusercontent.com/assets/1297448/6139047/335543c4-b13c-11e4-887a-e2186b141a8a.png)

**Comment by nevenisnoob-not-in-use** [comment] 2015-02-12 03:41
i got the same problem on my mac...

**Comment by tomByrer** [comment] 2015-02-16 16:19
http://famo.us/university/lessons/#/famous-101/displaying/3
Not working (no `Hello World`) on Firefox Dev 37.0a2 (2015-02-15) Win7.1_64.
Working on Chrome 40.0.2214.111 (64-bit) & IE 11.0.15.

**Comment by jdarowski** [comment] 2015-02-21 23:42
![zrzut ekranu 2015-02-22 00 39 28](https://cloud.githubusercontent.com/assets/5173618/6316573/5e14b4da-ba2b-11e4-88b4-93bba3510510.png)

I can't see the page either.
OS X 10.10.2, Chrome 40.0.2214.115 (and also latest Safari)

**Comment by matikucharski** [comment] 2015-03-17 18:49
Same for me on Chrome 40 on Ubuntu 14 and Windows 8.1. On Firefox works fine

**Comment by MylesBorins** [comment] 2015-04-08 07:37
Closing for now, this is inconsistent and we won't be fixing before the next version of university

**Closed as completed by MylesBorins** 2015-04-08 07:37 UTC
Labels: bug, university
