### ISSUE TITLE
Scrollview breaks on touch swipe when paginated option is true and child nodes have size undefined

### ISSUE THREAD

**Issue by leestar** [Famous/famous#573] opened 2015-01-10 23:45 UTC
I created a codepen to demonstrate this. It uses famo.us / angular, although I believe this is a famo.us issue:

http://codepen.io/anon/pen/GgrMzv

Try using mouse scroll as well as loading this on any mobile browser. You will find that with mouse scroll on desktop it works, but on mobile it breaks. I think it is linked to the touch event. You can also try emulating mobile using Chrome's Developer Tools mobile emulation mode. It breaks there as well.

**Comment by MrNice** [comment] 2015-01-11 01:30
This code from @arkadyp:

Replacing calculatePayload inside famous/inputs/TouchSync.js with this fixes the problem.

 function calculatePayload (data) {
        var history = data.history;

        var currHistory = history[history.length - 1];
        var prevHistory = history[history.length - 2];
        
        var distantHistory = SyncUtils.getTimeHistoryPosition(history, this.options.timeSampleDuration);

        var distantTime = distantHistory.timestamp;
        var currTime = currHistory.timestamp;

        var diffX = currHistory.x - prevHistory.x;
        var diffY = currHistory.y - prevHistory.y;

        var velDiffX = currHistory.x - distantHistory.x;
        var velDiffY = currHistory.y - distantHistory.y;

        if (this.options.rails) {
            if (Math.abs(diffX) > Math.abs(diffY)) diffY = 0;
            else diffX = 0;

            if (Math.abs(velDiffX) > Math.abs(velDiffY)) velDiffY = 0;
            else velDiffX = 0;
        }

        var diffTime = Math.max(currTime - distantTime, MINIMUM_TICK_TIME);

        var velX = velDiffX / diffTime;
        var velY = velDiffY / diffTime;

        var scale = this.options.scale;
        var nextVel;
        var nextDelta;

        if (this.options.direction === TouchSync.DIRECTION_X) {
            nextDelta = scale * diffX;
            nextVel = scale * velX;
            this._position += nextDelta;
        }
        else if (this.options.direction === TouchSync.DIRECTION_Y) {
            nextDelta = scale * diffY;
            nextVel = scale * velY;
            this._position += nextDelta;
        }
        else {
            nextDelta = [scale * diffX, scale * diffY];
            nextVel = [scale * velX, scale * velY];
            this._position[0] += nextDelta[0];
            this._position[1] += nextDelta[1];
        }

        var payload = this._payload;
        payload.delta    = nextDelta;
        payload.velocity = nextVel;
        payload.position = this._position;
        payload.clientX  = data.x;
        payload.clientY  = data.y;
        payload.count    = data.count;
        payload.touch    = data.identifier;

        this._eventOutput.emit('update', payload);
    }

**Comment by leestar** [comment] 2015-01-11 06:29
I don't see this method in famous/inputs/TouchSync, famous v.0.3.4. 

Do you mean _handleMove()?

**Comment by MrNice** [comment] 2015-01-11 08:07
Ah, In my case I was using famo.us v 0.3.3, which is what's in the npm registry currently.

https://github.com/Famous/famous/blob/v0.3.3/src/inputs/TouchSync.js

**Comment by TheAlphaNerd** [comment] 2015-01-11 08:09
@MrNice I'd double check that.  0.3.4 was published to npm 24 days ago.

**Comment by MrNice** [comment] 2015-01-11 08:13
@TheAlphaNerd 

Oh, nvm, Browserify-seed locks in the exact famo.us version number, and I started my project a two weeks ago.

**Comment by TheAlphaNerd** [comment] 2015-01-11 08:15
Ahhh… yeah I set that up a bit back to make sure projects wouldn’t automatically upgrade.  While we are fairly vigilant at stopping api changes from propagating, sometimes there are unforeseen weird changes between cuts

I highly suggest the tool “david” to manage dependencies.  You can use it via the cli, or peek the badges in the repo (if you change the references in the read me)=

**Comment by leestar** [comment] 2015-01-11 08:18
So I'm looking at the TouchSync.js commit history - was this fixed at one point and then reverted?

**Comment by TheAlphaNerd** [comment] 2015-01-11 08:23
@leestar there was a fix that landed but it caused a very odd regression.  Due to people being out of the office on holidays we needed to revert the fix and re-evaluate the approach.  We hope to see an official fix land very soon.

**Comment by leestar** [comment] 2015-01-11 08:48
@TheAlphaNerd Gotcha. Thanks for the info. As a workaround I have to manually compute view/surface dimensions. Looking forward to this fix!

**Comment by TheAlphaNerd** [comment] 2015-01-15 19:00
Fix should be landing soon!

**Comment by MylesBorins** [comment] 2015-04-08 07:30
Closing as I think a fix has landed. Please reopen if neccessary

**Closed by MylesBorins** 2015-04-08 07:30 UTC
Labels: bug
