### ISSUE TITLE
v3-beta: Safari mobile viewport gets "stuck" when keyboard closes.

### ISSUE THREAD

**Issue by trobbertze** [Famous/famous#317] opened 2014-09-23 10:03 UTC
In v3-beta and Safari mobile , when one has surfaces outside and underneath the viewable area, the viewport does not return to the correct position after closing the soft keyboard.

Here is a code snippet to reproduce:

<pre><code>
define(function(require, exports, module) {
    'use strict';
    var Engine = require('famous/core/Engine');
    var Modifier = require('famous/core/Modifier');
    var Transform = require('famous/core/Transform');
    var Surface = require('famous/core/Surface');
    var InputSurface = require('famous/surfaces/InputSurface');

    var context = Engine.createContext();

    context.setPerspective(1000);

    var surface = new Surface({
      size: [undefined, undefined],
      properties: {
        backgroundColor: 'red'
      }
    });

    context.add(surface);

    var inputSurface = new InputSurface({
      size: [200, 40],
      placeholder: 'Enter a value'
    });

    context.add(new Modifier({
      align: [0, 0.5]
    })).add(inputSurface);

    var surface2 = new Surface({
      size: [undefined, undefined],
      properties: {
        backgroundColor: 'blue'
      }
    });

    context.add(new Modifier({
      align: [0, 1]
    })).add(surface2);

});
</code></pre>

**Comment by istvanskeri** [comment] 2015-02-06 03:04
My scrollview content gets pushed out of view after the onscreen keyboard opens and can't scroll all the way up again after keyboard closes. I tried to apply the css fix body position absolute but issue is still happening. This bug is preventing us from launching our app. Please advise.

**Comment by antoniobrandao** [comment] 2015-03-13 18:04
I have the same problem. Viewport goes up on opening the keyboard, and then doesn't return to it's original position after closing the keyboard...

**Comment by leestar** [comment] 2015-03-13 22:56
Bumping this issue, although for me this happens on Android. I implemented a pure CSS workaround, which prevents the app from jumping up, but potentially hides the input bar. Basically the root node of my app has style:

#app {
  position: fixed;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
}

The problem is caused by having "bottom: 0", which causes the app to "jump up" when the keyboard slides out. So I changed it to:

#app {
  position: fixed;
  top: 0;
  right: 0;
  bottom: auto;
  height: 9000px;
  left: 0;
}

Setting the height to a large number guarantees that the body of the app renders, provided the children heights are well-defined. Depending on your specific implementation, YMMV.

Looking forward to a real solution as this is a critical bug, please fix this Famo.us team! :)

**Comment by MylesBorins** [comment] 2015-04-08 06:52
@michaelobriena looks like something still on the docket

**Closed** 2015-05-22 08:45 UTC
Labels: bug, mobile, wontfix

**Comment by DSRoden** [comment] 2015-07-22 13:29
Sorry, I can't tell if this issue was resolved? I'm experiencing a similar problem.
