### ISSUE TITLE
Beware of overflow: hidden, it breaks z-translation quite badly

### ISSUE THREAD

**Issue by IjzerenHein** [Famous/famous#493] opened 2014-11-24 11:06 UTC
Hi, I've come across a very annoying browser issue that causes the z-translation to not be respected. It happens to renderables inside a ContainerSurface using 'overflow: hidden'. Basically, the z-translation is no longer respected and instead the DOM ordering is used.
Obviously this is not a famo.us bug, but I thought you should know.
Test project: https://github.com/IjzerenHein/famous-zindex

Regards, Hein

**Comment by trusktr** [comment] 2015-02-08 19:55
@michaelobriena Can you post your version with the quadrants separated?

**Comment by trusktr** [comment] 2015-02-08 19:59
I made a bug for it in the Chromium bug tracker, https://code.google.com/p/chromium/issues/detail?id=456601&thanks=456601&ts=1423425515

**Comment by michaelobriena** [comment] 2015-02-08 20:15
Sorry, I actually just cleaned that up Friday!

**Comment by trusktr** [comment] 2015-02-08 20:21
No prob. hehe

**Comment by trusktr** [comment] 2015-02-13 22:17
Looks like they've confirmed it is a bug on their side: https://code.google.com/p/chromium/issues/detail?id=456601#c2

**Comment by trusktr** [comment] 2015-02-16 19:28
Update: The chromium devs have found the version that caused the break, and are looking to fix it.

**Comment by jordangarside** [comment] 2015-03-10 11:06
Is this the bug I'm experiencing on my [page](http://www.jordangarside.com/)?
My `overflow: hidden` is broken on my canvas container, and z-translation isn't respected.

Only happens on Chrome Mobile, both 4.4 and 5.0.3. (Firefox Mobile works fine)

Source is available [here](https://github.com/jordangarside/jordangarside).

**Comment by trusktr** [comment] 2015-03-22 20:27
@jordangarside What's the expected behavior? What should I see vs what we're actually seeing?

**Comment by zackbrown** [comment] 2015-03-23 01:28
I believe Chrome fixed this at one point a few months ago and then regressed.

The bug appears to occur specifically when **both** `transform-style: preserve-3d` and `overflow: hidden` are on the **same element.** A solution that has worked in the past for Chrome is to use two containers:  an outer container with `overflow: hidden` and an inner container, a child of the former, with `transform-style: preserve-3d`.

For example, @jordangarside in the example you linked, if you use to chrome inspector to remove the `overflow: hidden` property from `#mainCtx`, (since that element's parent, `.famous-root` also has `overflow: hidden` and since `#mainCtx` has `transform-style: preserve-3d`) z-translation works as expected.

**Comment by michaelobriena** [comment] 2015-06-24 17:53
This has been fixed in Chrome

**Closed by michaelobriena** 2015-06-24 17:53 UTC
Labels: bug, EPIC, vendor bug

**Comment by IjzerenHein** [comment] 2015-06-24 19:29
Awesome! Which version was that?

**Comment by michaelobriena** [comment] 2015-06-24 23:48
@IjzerenHein Unfortunately all I have for you is sometime between today and Nov 24th 2014

**Comment by IjzerenHein** [comment] 2015-06-25 07:49
Alright, well thanks for sharing that Michael!
